// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmTyhoasrUyFBUgAc-ufsyjj4TN7F2ZWk',
    appId: '1:1012664856549:web:7e042770689fb82ab6890c',
    messagingSenderId: '1012664856549',
    projectId: 'sotulub-55311',
    authDomain: 'sotulub-55311.firebaseapp.com',
    storageBucket: 'sotulub-55311.appspot.com',
    measurementId: 'G-VLK41G4E6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmYaZD-QT-KBaVN6xchYZtcZXgV9Ngcvo',
    appId: '1:1012664856549:android:9d0ba2b9d24e55fdb6890c',
    messagingSenderId: '1012664856549',
    projectId: 'sotulub-55311',
    storageBucket: 'sotulub-55311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZMJtTLGI-NrYX0ZIPj8XVzqCpA3Jpf6c',
    appId: '1:1012664856549:ios:d85d3617ebb90b1ab6890c',
    messagingSenderId: '1012664856549',
    projectId: 'sotulub-55311',
    storageBucket: 'sotulub-55311.appspot.com',
    iosBundleId: 'com.example.sotulub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZMJtTLGI-NrYX0ZIPj8XVzqCpA3Jpf6c',
    appId: '1:1012664856549:ios:d85d3617ebb90b1ab6890c',
    messagingSenderId: '1012664856549',
    projectId: 'sotulub-55311',
    storageBucket: 'sotulub-55311.appspot.com',
    iosBundleId: 'com.example.sotulub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmTyhoasrUyFBUgAc-ufsyjj4TN7F2ZWk',
    appId: '1:1012664856549:web:76548070a8f9f9fab6890c',
    messagingSenderId: '1012664856549',
    projectId: 'sotulub-55311',
    authDomain: 'sotulub-55311.firebaseapp.com',
    storageBucket: 'sotulub-55311.appspot.com',
    measurementId: 'G-QCM5JC18ZL',
  );
}
